= {productname} Server Upgrade

Before running the upgrade command, it is recommended to to update the host operating system.
Updating the host operating system will also result in the update of the {productname} tooling such as the [literal]``mgradm`` tool.

.Procedure: Upgrading {productname} Server

. Refresh software repositories with [command]``zypper``:

+

[source,shell]
----
zypper ref
----

ifeval::[{mlm-content} == true]
. Depending on the host operating system, proceed with these steps:

+

For a transactional system such as {sl-micro}: ::

+

--

. Apply available updates with [command]``transactional-update``:

+

[source,shell]
----
transactional-update
----

. If updates were applied, [literal]``reboot``.

--

+

endif::[]

ifeval::[{uyuni-content} == true]
. Apply available updates with [command]``transactional-update``:

+

[source,shell]
----
transactional-update
----

. If updates were applied, [literal]``reboot``.

endif::[]

ifeval::[{mlm-content} == true]
For {sles}: ::

+

--

Update installed software with [command]``zypper``:

[source,shell]
----
zypper up
----

--

endif::[]

+

. The {productname} Server container can be updated using the following command:

+

[source,shell]
----
mgradm upgrade podman
----

+

This command will bring the status of the container up-to-date and restart the server.



.Upgrading to specific version
[NOTE]
====
If you do not specify the tag parameter, it will default to upgrading to the most recent version.
To upgrade to a specific version, provide the tag parameter with the desired image tag.
====

For more information on the upgrade command and its parameters, use the following command:

[source,shell]
----
mgradm upgrade podman -h
----


For air-gapped installations, first upgrade the container RPM packages, then run the [literal]``mgradm`` command.

ifeval::[{mlm-content} == true]

= How to apply a Program Temporary Fix (PTF) to a containerized SUSE Manager 5
. Situation
A Program Temporary Fix (PTF) was received to address an issue reported for a containerized SUSE Manager 5 installation.
Applying a containerized fix to SUSE Manager 5 is accomplished using the following command:

. Resolution
Applying a containerized fix to SUSE Manager 5 is accomplished using the following command:
[source,shell]
----
mgradm support ptf podman --ptf <PTFnumber> --user <accountID>
----
The *<PTFnumber>* will be provided by a SUSE Support representative.
The *<accountID>* can be found in the SUSE Customer Center account, either to the right of the company name or on the left hand side in the navigation frame in grey font under the company name.
Make sure to select the account the SUSE Manager installation is registered to.

[NOTE]
====
*The starting letter of the "accountID" needs to be specified in lower case, similar to how it is in the provided PTF registry link.*
====
In case the issue has not been properly identified, a tentative fix may be provided as a TEST build first.
This is applied using:
[source,shell]
----
mgradm support ptf podman --test <TESTnumber> --user <accountID>
----
.Additional Information
PTFs provided via registry.suse.com are only created for the account as identified by a provided SUSE Manager supportconfig (created using "mgradm support config").
This data tar-ball is the required base information for a SUSE Manager support request. A supportconfig created directly on the SLE Micro instance running the container is not sufficient.
endif::[]
